---
- name: create servers
  hosts: localhost
  gather_facts: False
  vars:
    sl_datacenter: dal09
    sl_ssh_key: 926125
    sl_vlan: 1919743
    etc_hosts: ~

  tasks:
    - name: create mirror server
      sl_vm:
        hostname: "{{ item }}"
        domain: cuttle-demo.com
        datacenter: "{{ sl_datacenter|default('dal09') }}"
        tags: "{{ item }},mirror,control_dashboard,cuttle,cuttle-env-infra"
        hourly: True
        private: False
        dedicated: False
        local_disk: True
        cpus: 2
        memory: 2048
        disks: [25,100]
        os_code: UBUNTU_LATEST
        private_vlan: "{{ sl_vlan|default(omit) }}"
        wait: no
        ssh_keys: "{{ sl_ssh_key|default(omit) }}"
      with_items:
        - mirror01
    - name: create monitor server
      sl_vm:
        hostname: "{{ item }}"
        domain: cuttle-demo.com
        datacenter: "{{ sl_datacenter|default('dal09') }}"
        tags: "{{ item }},cuttle,cuttle-env-infra,control_dashboard,monitor,sensu,graphite,percona,percona_primary,rabbitmq,grafana,flapjack,netdata_dashboard"
        hourly: True
        private: False
        dedicated: False
        local_disk: True
        cpus: 2
        memory: 4096
        disks: [25,100]
        os_code: UBUNTU_LATEST
        private_vlan: "{{ sl_vlan|default(omit) }}"
        wait: no
        ssh_keys: "{{ sl_ssh_key|default(omit) }}"
      with_items:
        - monitor01

    - name: create elk server
      sl_vm:
        hostname: "{{ item }}"
        domain: cuttle-demo.com
        datacenter: "{{ sl_datacenter|default('dal09') }}"
        tags: "{{ item }},cuttle,cuttle-env-infra,control_dashboard,netdata_dashboard,elk,elasticsearch,kibana,logstash"
        hourly: True
        private: False
        dedicated: False
        local_disk: True
        cpus: 2
        memory: 4096
        disks: [25,100]
        os_code: UBUNTU_LATEST
        private_vlan: "{{ sl_vlan|default(omit) }}"
        wait: no
        ssh_keys: "{{ sl_ssh_key|default(omit) }}"
      with_items:
        - elk01
        - elk02
