---
- name: create servers
  hosts: localhost
  gather_facts: False
  vars:
    sl_datacenter: dal09
    sl_ssh_key: 926125
    sl_vlan: 1919743
    etc_hosts: ~

  tasks:
    - name: create bastion server
      sl_vm:
        hostname: "{{ item }}"
        domain: cuttle-demo.com
        datacenter: "{{ sl_datacenter|default('dal09') }}"
        tags: "bastion,cuttle,{{ item }},cuttle-env-bastion"
        hourly: True
        private: False
        dedicated: False
        local_disk: True
        cpus: 1
        memory: 2048
        disks: [25]
        os_code: UBUNTU_LATEST
        private_vlan: "{{ sl_vlan|default(omit) }}"
        wait: no
        ssh_keys: "{{ sl_ssh_key|default(omit) }}"
      with_items:
        - bastion01

    - name: create ttyspy server
      sl_vm:
        hostname: "{{ item }}"
        domain: cuttle-demo.com
        datacenter: "{{ sl_datacenter|default('dal09') }}"
        tags: "ttyspy-server,cuttle,{{ item }},cuttle-env-bastion"
        hourly: True
        private: False
        dedicated: False
        local_disk: True
        cpus: 1
        memory: 1024
        disks: [25,25]
        os_code: UBUNTU_LATEST
        wait: no
        private_vlan: "{{ sl_vlan|default(omit) }}"
        ssh_keys: "{{ sl_ssh_key|default(omit) }}"
      with_items:
        - ttyspy01
